### ISSUE TITLE
how to set size of the eidtor?

### ISSUE THREAD

**Issue by zouchengzhuo** [lepture/editor#100]
i want to add  it's height ,but don't know how to config

**Comment by MaicolBen** [comment]
@zouchengzhuo What do you mean? You can do that with css:
```
.CodeMirror {
    height: 1000px !important;
}
```

**Comment by ryanhageman** [comment]
Is this still an issue?

**Comment by MaicolBen** [comment]
@ryanhageman close it, the issuer didn't reply
