### ISSUE TITLE
How to get HTML content from the editor

### ISSUE THREAD

**Issue by alexbagirov** [lepture/editor#87]
For example I have embedded Editor on the page and I need to write something, save it in MySQL and show as HTML on another page. How it is possible to do so?

Thanks.

**Comment by lepture** [comment]
@alexbagirov get the markdown content, render the content with a markdown parser.

**Comment by alexbagirov** [comment]
@lepture, ok, I see that I can do it with `editor.codemirror.getValue();` but how can I transfer that content to PHP for example?

**Comment by alexbagirov** [comment]
Also how can I load a page with Editor and put some Markdown text in it automatically?
Do I have to just use it as <textarea>Needed text</textarea>?

**Comment by francistm** [comment]
@alexbagirov you can post your data through a `<textarea />` tag, also you can put some markdown in it. like below:

```php
<textarea name="content"><?php echo $markdown_content ?></textarea>
```

**Comment by alexbagirov** [comment]
@francistm, so if I add some more elements to this form and submit it all it will just put all the content to the <textarea>?

**Comment by cben** [comment]
Before submitting the textarea, don't forget to sync CodeMirror's content
into it using cm.save().
[https://codemirror.net/doc/manual.html#fromTextArea]

**Comment by alexbagirov** [comment]
@cben, but don't you think that text from the editor is already in the `<textarea>`?

If not then how to sync it?

**Comment by alexbagirov** [comment]
Well, it seems to be working for me without any syncing :smile:

**Comment by cben** [comment]
See CodeMirror doc I linked.
CM hides the text area since it does it's own rendering, and (for performance) doesn't constantly update the textarea.
However it does automagically "wire up the form of that textarea (if any) to make sure the editor contents are put into the textarea when the form is submitted" which explains why it worked for you.
Anyway, I'd call `editor.codemirror.save()` to be sure.
