### ISSUE TITLE
Ability to instantiate more than one per page

### ISSUE THREAD

**Issue by jackmcdade** [lepture/editor#9]
Is there any way to instantiate more than one per page? Perhaps by targeting a class instead of the `<textarea>`?

**Comment by Riari** [comment]
I know this is an old issue, but I ran into this while searching and thought I would post my jQuery solution here for anyone else who lands here too:

    $( '.editor' ).each( function() {
        var editor = new Editor( {
            element: $( this )[0]
        } );

        editor.render();
    } );
