### ISSUE TITLE
Can we add more icon in toolbar? like </> for code

### ISSUE THREAD

**Issue by hjspku** [lepture/editor#96]
Can we add more icon in toolbar? like </> for code

**Comment by WesCossick** [comment]
[SimpleMDE](https://github.com/NextStepWebs/simplemde-markdown-editor/) is an improved and more actively maintained project built off of this editor. You may want to look into that project. It supports most of the changes you've been requesting.

**Comment by MaicolBen** [comment]
Yes it is done in https://github.com/lepture/editor/pull/73
It is in the default toolbar, but it isn't in the demo.
